// See https://github.com/dialogflow/dialogflow-fulfillment-nodejs
// for Dialogflow fulfillment library docs, samples, and to report issues
'use strict';
const request = require('jsonrequest');

exports.handler = async (event, context, callback) => {
  let stops = [
    { stop: 'Downtown Interchange', id: '1' },
    { stop: 'Downtown Interchange', id: '2' },
    { stop: 'Softball Complex', id: '100' },
    { stop: 'Macbride Hall', id: '120' },
    { stop: 'IMU', id: '125' },
    { stop: 'Iowa Ave - English Philosophy Building, IMU', id: '145' },
    { stop: 'Iowa Ave - English Philosophy Building, IMU', id: '146' },
    { stop: 'Elliot St @ Carver Hawkeye Arena', id: '241' },
    { stop: 'Newton & Lincoln', id: '245' },
    { stop: 'Dental College', id: '246' },
    { stop: 'VA Loop', id: '250' },
    { stop: 'Newton Rd - VA Hospital', id: '253' },
    { stop: 'Newton Rd - VA Hospital', id: '254' },
    { stop: 'Newton Rd - MERF', id: '256' },
    { stop: 'Newton Rd Ramp', id: '257' },
    { stop: 'Newton Rd - UI Student Health', id: '263' },
    { stop: 'Pappajohn Biomedical Discovery Building', id: '264' },
    { stop: '12th Avenue & North Ridge Dr', id: '340' },
    { stop: '12th Ave & North Ridge Dr', id: '341' },
    { stop: '12th Ave & South Ridge Dr', id: '342' },
    { stop: '12th Ave & South Ridge Dr', id: '343' },
    { stop: '12th Avenue & Liberty Ln East', id: '345' },
    { stop: '12th Ave & Liberty Ln', id: '346' },
    { stop: 'Holiday Rd & Oak Lake Park Rd', id: '350' },
    { stop: 'Holiday Rd & Oak Lake Park Rd', id: '351' },
    { stop: 'Holiday Rd & Westview', id: '354' },
    { stop: 'Holiday Rd & Eastview', id: '355' },
    { stop: 'Holiday Rd & High Country Rd', id: '360' },
    { stop: 'Holiday Rd & Olde Hickory Rd', id: '361' },
    { stop: 'Holiday Rd & 1st Ave', id: '365' },
    { stop: 'Holiday Rd & 1st Ave', id: '366' },
    { stop: '1st Ave & Highway 6', id: '385' },
    { stop: 'Washington St & Madison St', id: '822' },
    { stop: 'Mayflower Hall', id: '1000' },
    { stop: 'Church St North', id: '1010' },
    { stop: 'Church St South', id: '1011' },
    { stop: 'Currier Hall', id: '1015' },
    { stop: 'Burge Hall', id: '1016' },
    { stop: 'PBB', id: '1021' },
    { stop: 'Clinton &  Iowa', id: '1030' },
    { stop: 'Clinton &  College', id: '1034' },
    { stop: 'Voxman Music Building', id: '1039' },
    { stop: 'Clinton &  Prentiss', id: '1040' },
    { stop: 'Main Library', id: '1050' },
    { stop: 'Communications Center', id: '1051' },
    { stop: 'ERF', id: '1060' },
    { stop: 'Madison St/Lot 11', id: '1064' },
    { stop: 'Prentiss &  Madison', id: '1070' },
    { stop: 'WCTC 2,4,6,8', id: '2000' },
    { stop: 'Arena on Hawkins', id: '2017' },
    { stop: 'Arena East', id: '2020' },
    { stop: 'Arena West', id: '2022' },
    { stop: 'Finkbine Entrance', id: '2025' },
    { stop: 'Finkbine North', id: '2030' },
    { stop: 'Finkbine South', id: '2031' },
    { stop: 'Dental on Elliott', id: '2040' },
    { stop: 'Carver Hawkeye Arena', id: '2041' },
    { stop: 'Family Care', id: '2070' },
    { stop: 'Melrose Court', id: '2071' },
    { stop: 'Rienow Hall', id: '2080' },
    { stop: 'Slater Hall', id: '2081' },
    { stop: 'Law Building', id: '2085' },
    { stop: 'Art Building West', id: '2100' },
    { stop: 'Art Building', id: '2101' },
    { stop: 'Riverside &  River St', id: '2105' },
    { stop: 'Theatre Building', id: '2106' },
    { stop: 'Hancher/Park Rd', id: '2110' },
    { stop: 'Hancher Lot East', id: '2114' },
    { stop: 'Hancher West', id: '2115' },
    { stop: 'Hancher/North Riverside', id: '2120' },
    { stop: 'Levitt Center', id: '2121' },
    { stop: 'East Lot ', id: '3001' },
    { stop: 'Old Hospital Road North', id: '3002' },
    { stop: 'Old Hospital Road South', id: '3003' },
    { stop: 'IREH East', id: '3010' },
    { stop: 'IREH West', id: '3011' },
    { stop: 'Hygenic Lab West', id: '3014' },
    { stop: 'Hygenic Lab East', id: '3015' },
    { stop: 'BioVenture West', id: '3016' },
    { stop: 'BioVenture East', id: '3017' },
    { stop: 'IDT', id: '3020' },
    { stop: 'MediRevv', id: '3021' },
    { stop: 'SSB', id: '3025' },
    { stop: 'Stem West', id: '3028' },
    { stop: 'STEM East', id: '3029' },
    { stop: 'Oakdale Blvd & 12th Avenue', id: '3035' },
    { stop: '12th Avenue &  Oakdale Blvd', id: '3036' },
    { stop: 'IRL West', id: '3072' },
    { stop: 'IRL East', id: '3073' },
    { stop: 'Hawkeye Park Road at Aspire', id: '3104' },
    { stop: 'Aspire', id: '3106' },
    { stop: 'Recreation Fields North', id: '3110' },
    { stop: 'Recreation Fields South', id: '3111' },
    { stop: 'Hawk Lot 1', id: '3125' },
    { stop: 'Hawk Lot 2', id: '3130' },
    { stop: 'Prairie Meadow &  Hawk Dr North', id: '3140' },
    { stop: 'Prairie Meadow & Hawk Dr South', id: '3141' },
    { stop: 'Sports Medicine Clinic South', id: '3150' },
    { stop: 'Sports Medicine Clinic North', id: '3151' },
    { stop: 'Hall of Fame North', id: '3155' },
    { stop: 'Hall of Fame South', id: '3156' },
    { stop: 'Highway 6 & Hawkins', id: '4010' },
    { stop: 'Highway 6 & 1st Ave - Hardees', id: '4015' },
    { stop: '4th Ave & Highway 6', id: '4021' },
    { stop: '5th St & 3rd Ave', id: '4030' },
    { stop: '1st Ave & 5th St', id: '4031' },
    { stop: '6th Street & 4th Ave. (Temp)', id: '4050' },
    { stop: '4th Ave. & 6th St', id: '4055' },
    { stop: '7th St & 4th Ave Place', id: '4060' },
    { stop: '7th St & 4th Ave Place', id: '4061' },
    { stop: '7th St & 6th Ave', id: '4070' },
    { stop: '7th St & 6th Ave', id: '4071' },
    { stop: '7th St & 7th Ave', id: '4080' },
    { stop: '7th St & 7th Ave', id: '4081' },
    { stop: '7th St & 10th Ave', id: '4090' },
    { stop: '7th St & 10th Ave', id: '4091' },
    { stop: '7th St & 12th Ave', id: '4100' },
    { stop: '12th Ave & 7th St', id: '4101' },
    { stop: '8th St & 12th Ave', id: '4105' },
    { stop: '8th St & 14th Ave', id: '4110' },
    { stop: '14th Ave & 8th St', id: '4111' },
    { stop: '14th Ave & 9th St', id: '4120' },
    { stop: '14th Ave & 9th St', id: '4121' },
    { stop: '14th Ave & 10th St', id: '4130' },
    { stop: '10th St & 14th Ave', id: '4131' },
    { stop: '10th St & 17th Ave', id: '4140' },
    { stop: '10th St & 17th Ave', id: '4141' },
    { stop: '10th St & 20th Ave', id: '4160' },
    { stop: '10th St & 20th Ave', id: '4161' },
    { stop: '20th Ave & 10th St', id: '4162' },
    { stop: '10 th St & 10th St Ct', id: '4170' },
    { stop: '10th St &10th St Place', id: '4171' },
    { stop: '10th St & 22nd Ave', id: '4180' },
    { stop: '10th St & 22nd Ave', id: '4181' },
    { stop: '22nd Ave & 10th St', id: '4182' },
    { stop: '10th St & 23rd Ave', id: '4190' },
    { stop: '10th St & 23rd Ave', id: '4191' },
    { stop: '10th St & North Boston Way', id: '4200' },
    { stop: '10th St & 25th Ave', id: '4210' },
    { stop: 'Coral Ridge Mall', id: '4220' },
    { stop: '10th St & South Boston Way', id: '4230' },
    { stop: '23rd Ave & 9th St', id: '4240' },
    { stop: '9th St & Oakleaf St', id: '4250' },
    { stop: '9th St & 21st Ave', id: '4260' },
    { stop: '9th St & 21st Ave', id: '4261' },
    { stop: '22nd Ave & 10th St Place', id: '4265' },
    { stop: '9th St & 20th Ave Place', id: '4270' },
    { stop: '9th St & 20th Ave Place', id: '4271' },
    { stop: '9th St & 20th Ave', id: '4280' },
    { stop: '20th Ave & 9th St', id: '4281' },
    { stop: '20th Ave & 8th St', id: '4290' },
    { stop: '8th St & 20th Ave', id: '4291' },
    { stop: '20th Ave & 5th St', id: '4300' },
    { stop: '20th Ave & 5th St', id: '4301' },
    { stop: '5th St & 18th Ave - Coral Village', id: '4310' },
    { stop: '5th St & 18th Ave - Coral Village', id: '4311' },
    { stop: '5th St & 7th St - City Hall', id: '4320' },
    { stop: '5th St & 7th St - City Hall', id: '4321' },
    { stop: '5th St & 12th Ave - West Music', id: '4330' },
    { stop: '5th St & 12th Ave - Library', id: '4331' },
    { stop: '5th St & 8th Ave', id: '4360' },
    { stop: '5th St & 8th Ave', id: '4361' },
    { stop: '5th St & 4th Ave', id: '4370' },
    { stop: '4th Ave & 5th St', id: '4371' },
    { stop: '5th St & 3rd Ave', id: '4380' },
    { stop: 'Ponseti Way', id: '4975' },
    { stop: 'Intermodal', id: '5000' },
    { stop: 'Highway 6 & 6th Ave', id: '5010' },
    { stop: 'Highway 6 & 10th Ave', id: '5020' },
    { stop: '9th St & Ponseti Way', id: '5025' },
    { stop: 'Highway 6 Park Place Stop', id: '5030' },
    { stop: 'Highway 6 & 22nd Ave.', id: '5040' },
    { stop: 'Highway 6 & 22nd Ave', id: '5041' },
    { stop: 'Commerce Dr & Commercial Park', id: '5060' },
    { stop: 'Commerce Dr & Commercial Park', id: '5061' },
    { stop: 'Commercial Park & Heartland Dr', id: '5070' },
    { stop: 'Commercial Park & Heartland Dr', id: '5071' },
    { stop: 'Heartland Place & Heartland Dr', id: '5080' },
    { stop: 'Goodwill', id: '5090' },
    { stop: 'Heartland Place & Heartland Dr', id: '5095' },
    { stop: 'Holiday Rd & North Coral St', id: '5100' },
    { stop: 'Holiday Rd & North Coral St - Hope House', id: '5101' },
    { stop: 'Holiday Rd - North Ridge Park', id: '5110' },
    { stop: 'Holiday Rd - North Ridge Park', id: '5111' },
    { stop: 'Lynncrest Dr & Holiday Rd.', id: '5120' },
    { stop: 'Lynncrest Dr & Holiday Rd', id: '5121' },
    { stop: 'Lynncrest Dr & North Ridge Dr', id: '5130' },
    { stop: 'North Ridge Dr & Lynncrest Dr', id: '5131' },
    { stop: 'North Ridge Dr & Waterford', id: '5140' },
    { stop: 'North Ridge Dr & Waterford', id: '5141' },
    { stop: 'North Ridge Dr & Farrel Dr', id: '5150' },
    { stop: 'North Ridge Dr & Farrel Dr', id: '5151' },
    { stop: 'North Ridge Dr & 12th Ave.', id: '5160' },
    { stop: 'Liberty Ln & 12th Ave', id: '5181' },
    { stop: 'Liberty Ln & Holiday Rd', id: '5190' },
    { stop: 'Holiday Rd & Liberty Ln', id: '5191' },
    { stop: 'Holiday Rd & 12th Ave.', id: '5200' },
    { stop: '12th Ave & Holiday Rd', id: '5201' },
    { stop: 'Holiday Rd & 12th Ave', id: '5203' },
    { stop: '12th Ave & Ozark Ridge', id: '5210' },
    { stop: '12th Ave & Ozark Ridge', id: '5211' },
    { stop: '12th Ave & 10th St', id: '5220' },
    { stop: '10th St & 12th Ave', id: '5222' },
    { stop: '10th St & 12th Ave', id: '5223' },
    { stop: 'Highway 6 - Dairy Queen', id: '5250' },
    { stop: 'Holiday Rd & Southridge Dr', id: '5280' },
    { stop: 'Holiday Rd & Waterford', id: '5290' },
    { stop: 'Front St & Vandello', id: '5800' },
    { stop: 'Front & Vandello', id: '5801' },
    { stop: 'Front St & Weston', id: '5810' },
    { stop: 'Front St & Weston', id: '5811' },
    { stop: 'Front St & Zeller', id: '5820' },
    { stop: 'Front St & Zeller', id: '5821' },
    { stop: 'Front St & Cherry St', id: '5830' },
    { stop: 'Front St & Cherry St', id: '5831' },
    { stop: 'North Liberty Rec Center', id: '5840' },
    { stop: 'Golfview Dr & Heidi Ln', id: '5850' },
    { stop: 'Golfview Dr & Rebecca St', id: '5851' },
    { stop: 'Golfview Dr at the Holiday MH Park', id: '5855' },
    { stop: 'Golfview Dr at the Holiday MH Park', id: '5856' },
    { stop: 'Fairview Ln & Augusta Circle', id: '5860' },
    { stop: 'Fairview Ln & Andrews Ct', id: '5861' },
    { stop: 'Sugar Creek Ln & Augusta Circle', id: '5865' },
    { stop: 'Sugar Creek Ln & Augusta Circle', id: '5866' },
    { stop: 'Sugar Creek Ln & Praire Ridge Rd', id: '5870' },
    { stop: 'Sugar Creek Ln & Praire Ridge Rd', id: '5871' },
    { stop: 'Sugar Creek Ln & W Zeller St', id: '5875' },
    { stop: 'W Zeller St & Sugar Creek Ln', id: '5876' },
    { stop: '6th St & 5th Ave - Coralville Central', id: '5910' },
    { stop: '6th St & 6th Ave', id: '5920' },
    { stop: 'Northwest Jr. High', id: '5930' },
    { stop: '8th St & 18th Ave', id: '5940' },
    { stop: '18th Ave. & 20th Ave', id: '5950' },
    { stop: 'Court St  & Dubuque St', id: '7002' },
    { stop: 'Court St  & Dubuque St', id: '7003' },
    { stop: 'Court St Transportation Center', id: '7004' },
    { stop: 'Court St  & Gilbert St', id: '7005' },
    { stop: 'Court St  & Maiden Ln', id: '7006' },
    { stop: 'Gilbert St & Prentiss St', id: '7007' },
    { stop: 'Gilbert St & Bowery St', id: '7008' },
    { stop: 'Gilbert St & Benton St', id: '7009' },
    { stop: 'Gilbert St & Benton St', id: '7010' },
    { stop: 'Gilbert St & Kirkwood Ave', id: '7011' },
    { stop: 'Gilbert St & Kirkwood Ave', id: '7012' },
    { stop: 'Kirkwood Ave & Gilbert St', id: '7013' },
    { stop: 'Gilbert St & 3rd Ave', id: '7014' },
    { stop: 'Gilbert St & 3rd Ave', id: '7015' },
    { stop: 'Highland Ave & Gilbert St', id: '7016' },
    { stop: 'Boyrum St @ Hy Vee', id: '7017' },
    { stop: 'Boyrum St @ Hy Vee', id: '7018' },
    { stop: 'Boyrum St & Southgate Ave', id: '7019' },
    { stop: 'Southgate Ave & Boyrum St', id: '7020' },
    { stop: 'Southgate Ave & Boyrum St', id: '7021' },
    { stop: 'Southgate Ave & Waterfront Dr', id: '7022' },
    { stop: 'Southgate Ave & Gilbert St', id: '7023' },
    { stop: 'Gilbert St & Stevens Dr', id: '7024' },
    { stop: 'Gilbert St @ Hills Bank', id: '7025' },
    { stop: 'Southgate Ave & Keokuk St', id: '7026' },
    { stop: 'Southgate & Keokuk St', id: '7027' },
    { stop: 'Keokuk St & Cross Park Ave', id: '7028' },
    { stop: 'Keokuk St & Cross Park Ave', id: '7029' },
    { stop: 'Sandusky Dr & Hickory Ct', id: '7030' },
    { stop: 'Sandusky Dr & Keokuk St', id: '7031' },
    { stop: 'Sandusky Dr & Broadway St', id: '7032' },
    { stop: 'Sandusky Dr & Broadway St', id: '7033' },
    { stop: 'Crosspark Ave 900 Block', id: '7034' },
    { stop: 'Crosspark Ave & Broadway St', id: '7035' },
    { stop: 'Broadway St 1900 Block', id: '7036' },
    { stop: 'Pepperwood Plaza', id: '7037' },
    { stop: 'Sandusky Dr & Taylor Dr', id: '7038' },
    { stop: 'Taylor Dr & Sandusky Dr', id: '7039' },
    { stop: 'Taylor Dr & Hollywood Blvd', id: '7040' },
    { stop: 'Hollywood Blvd Mid -block', id: '7041' },
    { stop: 'Hollywood Blvd & Sycamore St', id: '7042' },
    { stop: 'Hollywood Blvd & Delwood Dr', id: '7043' },
    { stop: 'Hollywood Blvd & Grantwood St', id: '7044' },
    { stop: 'Hollywood Blvd & Fairmeadows Blvd', id: '7045' },
    { stop: 'Lakeside Dr & Hwy 6', id: '7049' },
    { stop: 'Frontage Rd', id: '7050' },
    { stop: 'Riviera Dr & Frontage Rd', id: '7051' },
    { stop: 'Lakeside Dr & Whispering Prairie Ave', id: '7052' },
    { stop: 'Lakeside Dr & Nevada Ave', id: '7053' },
    { stop: 'Lakeside Dr & Miami Dr', id: '7054' },
    { stop: 'Miami Dr & California Ave', id: '7055' },
    { stop: 'California Ave & Union Ave', id: '7056' },
    { stop: 'California Ave & Grantwood St', id: '7057' },
    { stop: 'California Ave & Sycamore St', id: '7058' },
    { stop: 'Burns Ave & California Ave', id: '7059' },
    { stop: 'Burns Ave & Taylor Dr', id: '7060' },
    { stop: 'Sycamore Mall', id: '7061' },
    { stop: 'Highland Ave - Kirkwood College ', id: '7062' },
    { stop: 'Highland Ave & Pine St', id: '7064' },
    { stop: 'Highland Ave & Franklin St', id: '7065' },
    { stop: 'Highland Ave & Ridge', id: '7066' },
    { stop: 'Highland Ave & Lukurk St', id: '7067' },
    { stop: 'Highland Ave & Keokuk St', id: '7068' },
    { stop: 'Highland Ave & Boyrum St', id: '7069' },
    { stop: 'Highland Ave & Gilbert Court', id: '7070' },
    { stop: 'Benton St & Clinton St', id: '7071' },
    { stop: 'Benton St & Capitol St', id: '7072' },
    { stop: 'Capitol St & Benton St ', id: '7073' },
    { stop: 'Capitol St & Prentiss St', id: '7074' },
    { stop: 'Capitol St & Prentiss St', id: '7075' },
    { stop: 'Capitol St & Harrison St', id: '7076' },
    { stop: 'Court St & Capitol St', id: '7077' },
    { stop: 'Court St & Madison St', id: '7078' },
    { stop: 'Madison St @ UI Lindquist Center', id: '7079' },
    { stop: 'UI Main Library', id: '7080' },
    { stop: 'Madison St & Washington St', id: '7081' },
    { stop: 'Washington St & Madison St', id: '7082' },
    { stop: 'Iowa Ave & Madison St', id: '7090' },
    { stop: 'Dubuque St & Market St', id: '7091' },
    { stop: 'Dubuque St & Davenport St', id: '7092' },
    { stop: 'Dubuque St & Church St', id: '7093' },
    { stop: 'Gilbert St & Bowery St', id: '7100' },
    { stop: 'Bowery St & Van Buren St', id: '7101' },
    { stop: 'Bowery St  & Johnson St', id: '7102' },
    { stop: 'Bowery St & Johnson St', id: '7103' },
    { stop: 'Bowery St  & Dodge St', id: '7104' },
    { stop: 'Dodge St & Bowery St', id: '7105' },
    { stop: 'Dodge St & Walnut St', id: '7106' },
    { stop: 'Dodge St & Walnut St', id: '7107' },
    { stop: 'Kirkwood Ave & Dodge St', id: '7108' },
    { stop: 'Kirkwood Ave & Dodge St', id: '7109' },
    { stop: 'Kirkwood Ave & Keokuk St', id: '7110' },
    { stop: 'Kirkwood Ave & Keokuk St', id: '7111' },
    { stop: 'Kirkwood Ave & Howell St', id: '7112' },
    { stop: 'Kirkwood Ave & Summit St', id: '7113' },
    { stop: 'Kirkwood Ave & Franklin St', id: '7114' },
    { stop: 'Kirkwood Ave & Franklin St', id: '7115' },
    { stop: 'Kirkwood Ave & Roosevelt St', id: '7116' },
    { stop: 'Lower Muscatine Ave & Pine St', id: '7117' },
    { stop: 'Lower Muscatine Ave & Pine St', id: '7118' },
    { stop: 'Lower Muscatine Ave  & Spruce St', id: '7119' },
    { stop: 'Kirkwood Community College From Downtown', id: '7120' },
    { stop: 'Kirkwood Community College to Downtown', id: '7121' },
    { stop: 'Lower Muscatine Ave & Mall Dr', id: '7122' },
    { stop: 'Jefferson St & Van Buren St', id: '7123' },
    { stop: 'Eastdale Plaza', id: '7124' },
    { stop: 'Lower Muscatine Ave & Fairmeadows Blvd', id: '7125' },
    { stop: 'Hwy 6 East & Heinz Rd', id: '7126' },
    { stop: 'Heinz Rd & Hwy 6 East', id: '7127' },
    { stop: 'Commerce Dr & Liberty Dr', id: '7128' },
    { stop: 'Scott Blvd & Liberty Dr - ACT', id: '7129' },
    { stop: 'ACT', id: '7130' },
    { stop: 'Scott BLVD & Sytems Unlimited', id: '7131' },
    { stop: 'Heinz Rd & Scott Blvd', id: '7132' },
    { stop: 'ALPLA', id: '7133' },
    { stop: 'Eastdale Plaza', id: '7134' },
    { stop: 'Sycamore Mall Cinema Theater', id: '7135' },
    { stop: 'Muscatine Ave & Rundell St', id: '7151' },
    { stop: 'Washington St & Linn St - IC Library, Senior Center', id: '7200' },
    { stop: 'Washington St & Gilbert St - Iowa City City Hall', id: '7201' },
    { stop: 'Gilbert St & Washington St - IC City Hall', id: '7202' },
    { stop: 'College St & Gilbert St', id: '7203' },
    { stop: 'College and Gilbert', id: '7204' },
    { stop: 'Gilbert St & Jefferson St', id: '7205' },
    { stop: 'Market St & Linn St', id: '7206' },
    { stop: 'Clinton St & Jefferson St', id: '7207' },
    { stop: 'College St & Dodge St', id: '7209' },
    { stop: 'College St & Summit St', id: '7211' },
    { stop: 'College St & Summit St', id: '7212' },
    { stop: 'College St & Governor St', id: '7213' },
    { stop: 'Summit St & Court St', id: '7214' },
    { stop: 'Summit St & Bowery St', id: '7215' },
    { stop: ' Sheridan St - Longfellow Elementary', id: '7216' },
    { stop: 'Sheridan St & Roosevelt St', id: '7217' },
    { stop: 'Sheridan St & Oakland St', id: '7218' },
    { stop: 'Sheridan St & Rundell St', id: '7219' },
    { stop: 'Sheridan St & 7th Ave', id: '7220' },
    { stop: '7th Ave & F St', id: '7221' },
    { stop: 'F St & 6th Ave', id: '7222' },
    { stop: 'F St & Muscatine Ave', id: '7223' },
    { stop: 'Muscatine Ave & 4th Ave', id: '7224' },
    { stop: 'Muscatine Ave & 4th Ave', id: '7225' },
    { stop: 'Muscatine Ave & 2nd Ave - Walgreens ', id: '7226' },
    { stop: 'Musctine Ave & 2nd Ave - Walgreens Inbound', id: '7227' },
    { stop: '1st Ave @ Hy Vee', id: '7228' },
    { stop: 'D St & 3rd Ave', id: '7229' },
    { stop: 'Friendship St & Third Ave', id: '7230' },
    { stop: '3rd Ave & Friendship St', id: '7231' },
    { stop: 'Friendship St & 5th Ave', id: '7232' },
    { stop: 'Friendship St & Garden St', id: '7233' },
    { stop: 'Friendship St & 7th Ave', id: '7234' },
    { stop: '7th Ave & Court St', id: '7235' },
    { stop: 'Court St & 7th Ave', id: '7236' },
    { stop: 'Court St & 7th Ave', id: '7237' },
    { stop: 'College St & 7th Ave - City High School', id: '7238' },
    { stop: 'College St & Fairview St', id: '7239' },
    { stop: 'College St & Muscatine Ave', id: '7240' },
    { stop: 'Burlington St & Johnson St', id: '7241' },
    { stop: 'Burlington St & Johnson St', id: '7242' },
    { stop: 'Bulington St & Gilbert St - City Hall/Rec. Center', id: '7243' },
    { stop: 'Burlington St & Dubuque St', id: '7244' },
    { stop: 'Burlington St & Lucas St', id: '7245' },
    { stop: 'Burlington St & Lucas St', id: '7246' },
    { stop: 'Burlington St & Summit St', id: '7247' },
    { stop: 'Burlington St & Summit St', id: '7248' },
    { stop: 'Burlington St & Muscatine Ave', id: '7249' },
    { stop: 'Muscatine Ave & Burlington St', id: '7250' },
    { stop: 'Muscatine Ave & Court St', id: '7252' },
    { stop: 'Muscatine Ave & 7th Ave', id: '7253' },
    { stop: 'Muscatine Ave & 7th Ave', id: '7254' },
    { stop: 'Muscatine Ave & 5th Ave', id: '7255' },
    { stop: 'Muscatine Ave & 5th Ave', id: '7256' },
    { stop: 'Muscatine Ave & Wade St', id: '7257' },
    { stop: 'Muscatine Ave @ Hy Vee', id: '7258' },
    { stop: 'William St @Towncrest Medical Offices', id: '7259' },
    { stop: 'William St & Wayne Ave @ South East Junior High', id: '7260' },
    { stop: 'Wayne Ave & Arthur St ', id: '7261' },
    { stop: 'Wayne Ave & Dover St', id: '7262' },
    { stop: 'Wayne Ave & Village Rd', id: '7263' },
    { stop: 'Village Rd & Brighton Green', id: '7264' },
    { stop: 'Village Rd & Village Green Blvd', id: '7265' },
    { stop: 'Muscatine Ave & Maplewood Ln', id: '7266' },
    { stop: 'Muscatine Ave @ Autumn Park Apartments', id: '7267' },
    { stop: 'Muscatine Ave & Dover St', id: '7268' },
    { stop: 'Muscatine Ave & Arthur St', id: '7269' },
    { stop: 'Court St & Muscatine Ave', id: '7301' },
    { stop: 'Court St & Muscatine Ave', id: '7302' },
    { stop: 'Court St & Morningside Dr', id: '7303' },
    { stop: 'Court St & Morningside Dr', id: '7304' },
    { stop: 'Court St & 4th Ave - City High School', id: '7307' },
    { stop: 'Court St & 2nd Ave', id: '7308' },
    { stop: 'Court St & 2nd Ave ', id: '7309' },
    { stop: 'Court St & 1st Ave', id: '7311' },
    { stop: 'Court St & Upland Ave', id: '7312' },
    { stop: 'Upland & Ave & Court St', id: '7313' },
    { stop: 'Court St & Terrace Rd', id: '7314' },
    { stop: 'Court St & Linden Court', id: '7315' },
    { stop: 'Court St & Westminster St', id: '7316' },
    { stop: 'Court St & Dartmouth St', id: '7317' },
    { stop: 'Court St & Friendship Ave', id: '7318' },
    { stop: 'Friendship St & Court St', id: '7319' },
    { stop: 'Friendship Ave & Arbor St', id: '7321' },
    { stop: 'Friendship Ave & Clover St', id: '7322' },
    { stop: 'Friendship Ave & Norwood Circle', id: '7323' },
    { stop: 'Friendship Ave & Meadow St', id: '7324' },
    { stop: 'Friendship Ave & Terrace Rd', id: '7325' },
    { stop: 'Upland Ave & Crestview Ave', id: '7326' },
    { stop: 'Court St  & Peterson St', id: '7327' },
    { stop: 'Court St  & Elmira St', id: '7328' },
    { stop: 'Court St  & Kenneth Dr', id: '7329' },
    { stop: 'Court St  & Camden Rd', id: '7330' },
    { stop: 'Arlington Dr & Court St', id: '7331' },
    { stop: 'Arlington Dr & Cumberland Ln', id: '7332' },
    { stop: 'Huntington Dr & Arlington Dr', id: '7333' },
    { stop: 'Huntington Dr & Cardigan Ln', id: '7334' },
    { stop: 'Huntington Dr & Court St', id: '7335' },
    { stop: 'Court St & Camden Rd', id: '7336' },
    { stop: 'Ashford Place & Chadwick Place', id: '7337' },
    { stop: 'Ashford Place & York Place', id: '7338' },
    { stop: 'York Place & Brentwood Ln', id: '7339' },
    { stop: 'Brentwood & Camden St', id: '7340' },
    { stop: 'Camden Rd & Ashford Place', id: '7341' },
    { stop: 'Court St & Kenneth Dr', id: '7342' },
    { stop: 'Court St & Lindeman Dr', id: '7343' },
    { stop: 'Scott Park Dr & Elgin Dr', id: '7344' },
    { stop: 'Regency Heights Apts.', id: '7345' },
    { stop: 'Scott Blvd & Lower West Branch Rd', id: '7346' },
    { stop: 'Lower West Branch Rd & Middlebury Rd', id: '7347' },
    { stop: 'Clinton St & Jefferson St', id: '7400' },
    { stop: 'Jefferson St & Linn St', id: '7401' },
    { stop: 'Jefferson St & Dodge St', id: '7403' },
    { stop: 'Jefferson St & Governor St', id: '7404' },
    { stop: 'Clapp St & Hotz Ave', id: '7405' },
    { stop: 'Clapp St & Rochester Ave', id: '7406' },
    { stop: 'Rochester Ave & Elizabeth St', id: '7407' },
    { stop: 'Rochester Ave & Pleasant St', id: '7408' },
    { stop: 'Rochester Ave & Pleasant St', id: '7409' },
    { stop: 'Rochester Ave & Memler Court', id: '7410' },
    { stop: 'Rochester Ave & Memler Court', id: '7411' },
    { stop: 'Rochester Ave & 7th Ave', id: '7412' },
    { stop: 'Rochester Ave & 7th Ave', id: '7413' },
    { stop: 'Rochester Ave & Ashwood Dr', id: '7414' },
    { stop: 'Rochester Ave & Windsor Court', id: '7415' },
    { stop: 'Rochester Ave & Rita Lyn Court', id: '7416' },
    { stop: 'Rochester Ave & Rita Lyn Court', id: '7417' },
    { stop: 'Regina Education Center', id: '7418' },
    { stop: 'Regina Education Center', id: '7419' },
    { stop: 'Rochester Ave & 1st Ave', id: '7420' },
    { stop: 'Rochester Ave & 1st Ave', id: '7421' },
    { stop: 'Rochester Ave & Post Rd', id: '7422' },
    { stop: 'Rochester Ave & Post Rd', id: '7423' },
    { stop: 'Rochester Ave & Mount Vernon Dr', id: '7424' },
    { stop: 'Mount Vernon Dr & Rochester Ave', id: '7425' },
    { stop: 'Rochester Ave & Larch Ln', id: '7426' },
    { stop: 'Amhurst St & Lower West Branch Rd', id: '7427' },
    { stop: 'Amhurst St & Tulane Ave', id: '7428' },
    { stop: 'Amhurst St & Hastings Ave', id: '7429' },
    { stop: 'Amhurst St @ Lemme Elementary', id: '7430' },
    { stop: 'Amhurst St & Oberlin St', id: '7431' },
    { stop: 'Amhurst St & Washington St', id: '7432' },
    { stop: 'Washington St & Raven St', id: '7433' },
    { stop: ' Washington St @ Lemme Elementary ', id: '7434' },
    { stop: 'Washington St & Westminster St', id: '7435' },
    { stop: 'Washington St & Green Mountain Dr', id: '7436' },
    { stop: 'Washington St & Mount Vernon Dr', id: '7437' },
    { stop: 'Mount Vernon Dr & Concord Circle', id: '7438' },
    { stop: 'Mount Vernon Dr 300 Block', id: '7439' },
    { stop: 'Market St & Governor St', id: '7440' },
    { stop: 'Market St & Dodge St', id: '7441' },
    { stop: 'North Dodge St & Market St', id: '7442' },
    { stop: 'Mercy Hospital', id: '7443' },
    { stop: 'Dubuque St & Fairchild St', id: '7450' },
    { stop: 'Dubuque St & Davenport St', id: '7451' },
    { stop: 'Dubuque St & Bloomington St', id: '7452' },
    { stop: 'Dubuque St & Market St', id: '7453' },
    { stop: 'Governor St & Jefferson St', id: '7500' },
    { stop: 'Governor St & Market St', id: '7501' },
    { stop: 'Governor St & Davenport St', id: '7502' },
    { stop: 'Governor St & Church St', id: '7503' },
    { stop: 'Governor St & Brown St', id: '7504' },
    { stop: 'Governor St & Governor St', id: '7505' },
    { stop: 'Governor St & North Dodge St', id: '7506' },
    { stop: 'North Dodge St & Summit St', id: '7507' },
    { stop: 'North Doge St @ Hy Vee', id: '7508' },
    { stop: 'North Dodge St @ Hy Vee', id: '7509' },
    { stop: 'Iowa City Community School District  Office', id: '7510' },
    { stop: 'Iowa City Community School District  Office', id: '7511' },
    { stop: 'North Dodge St & Scott Blvd', id: '7512' },
    { stop: 'ACT #1', id: '7513' },
    { stop: 'ACT #2', id: '7514' },
    { stop: 'ACT #3', id: '7515' },
    { stop: 'City High School PM', id: '7519' },
    { stop: 'Pearson Main Entrance', id: '7521' },
    { stop: 'Pearsons Dr & North Dodge St', id: '7522' },
    { stop: 'North Dodge St & ACT Circle', id: '7523' },
    { stop: 'North Dodge St & Bristol Dr', id: '7524' },
    { stop: 'Prairie du Chien Rd & North Dodge St', id: '7525' },
    { stop: 'Prairie du Chien Rd & Caroline Court', id: '7526' },
    { stop: 'Caroline Ave & Prairie du Chien Rd', id: '7527' },
    { stop: 'Whiting Ave & Kimball Rd', id: '7528' },
    { stop: 'Kimble Rd and Kimble Ave', id: '7529' },
    { stop: 'Governor St & Kimball Rd', id: '7530' },
    { stop: '919 North Dodge St', id: '7531' },
    { stop: '900 North Dodge St ', id: '7532' },
    { stop: 'North Dodge St & Brown St', id: '7533' },
    { stop: 'North Dodge St & Church-Horace Mann Elementary', id: '7534' },
    { stop: 'Eastdale Plaza', id: '7600' },
    { stop: '1st Ave @ South East Junior High', id: '7601' },
    { stop: 'City High School', id: '7602' },
    { stop: 'Arlington Dr & Canterbury Court', id: '7603' },
    { stop: 'Arlington Dr & American Legion Rd', id: '7604' },
    { stop: 'American Legion Rd & Scott Blvd', id: '7605' },
    { stop: 'Wellington Dr & Scott Blvd', id: '7606' },
    { stop: 'Scott Blvd #1', id: '7607' },
    { stop: 'Bon Aire Mobile Home Lodge', id: '7700' },
    { stop: 'Frontage Rd & Lakeside Dr', id: '7701' },
    { stop: 'Kirkwood Ave & Gilbert St', id: '7750' },
    { stop: 'Hydraulics Lab, Boyd Law School', id: '8000' },
    { stop: 'Hydraulics Lab, Boyd Law School', id: '8001' },
    { stop: 'Riverside Dr & Myrtle Ave', id: '8002' },
    { stop: 'Riverside Dr & Myrtle Ave', id: '8003' },
    { stop: 'Riverside Dr & Riverside Court', id: '8004' },
    { stop: 'Benton St & Riverside Dr', id: '8005' },
    { stop: 'Riverside Dr & Benton St', id: '8006' },
    { stop: 'Benton St & Giblin Dr', id: '8007' },
    { stop: 'Benton St & Hudson Ave', id: '8008' },
    { stop: 'Miller Ave & Hwy 1 West', id: '8009' },
    { stop: 'Hwy 1 West & Miller Ave', id: '8010' },
    { stop: 'Hwy 1 & Ruppert Rd', id: '8011' },
    { stop: 'Ruppert Rd & Hwy 1 West', id: '8012' },
    { stop: 'Westport Plaza 1', id: '8013' },
    { stop: 'Walmart', id: '8014' },
    { stop: 'Hwy 1 West @ Slagers', id: '8015' },
    {
      stop: 'Riverside Dr & Hwy 6 - Gateway Center, Iowa City Transit',
      id: '8016'
    },
    {
      stop: 'Riverside Dr & Hwy 6 - Gateway Center, Iowa City Transit',
      id: '8017'
    },
    { stop: 'Riverside Dr & Ruppert Rd', id: '8018' },
    { stop: 'Iowa City Airport', id: '8020' },
    { stop: 'Colonial Lns', id: '8021' },
    { stop: 'Riverside Dr/ Old Hwy 218 & South Riverside Dr', id: '8022' },
    { stop: 'Thatcher/Baculus Trailer Park', id: '8023' },
    { stop: 'South Riverside Dr & Commercial Dr', id: '8024' },
    { stop: 'S. Riverside Dr', id: '8025' },
    { stop: 'VA Hospital - Woolf Ave', id: '8050' },
    { stop: 'VA Hospital - Woolf Ave', id: '8051' },
    { stop: 'Woolf Ave & Bayard St', id: '8052' },
    { stop: 'Woolf  Ave & Rider St', id: '8053' },
    { stop: 'Woolf Ave & River St', id: '8054' },
    { stop: 'River St & Woolf Ave', id: '8055' },
    { stop: 'River St & Lee St', id: '8056' },
    { stop: 'Lee St & Highwood St', id: '8058' },
    { stop: 'Lee St & Highwood St', id: '8059' },
    { stop: 'Lee St & Park Rd', id: '8060' },
    { stop: 'Park Rd & Normandy Dr', id: '8061' },
    { stop: 'Park Rd & Lexington Ave', id: '8062' },
    { stop: 'Park Rd & Lexington Ave', id: '8063' },
    { stop: 'Park Rd & Magowen Ave', id: '8064' },
    { stop: 'Park Rd & Beldon Ave', id: '8066' },
    { stop: 'Park Rd & Beldon Ave', id: '8067' },
    { stop: 'Upper City Park', id: '8068' },
    { stop: 'Upper City Park', id: '8069' },
    { stop: 'Dubuque St & Park Rd', id: '8073' },
    { stop: 'Foster Rd & Dubuque St', id: '8078' },
    { stop: 'Foster Rd & Laura Dr', id: '8079' },
    { stop: 'Laura Dr & Foster Rd', id: '8080' },
    { stop: 'Foster Rd & Laura Dr-Church', id: '8081' },
    { stop: 'Forest View Trailer Park', id: '8082' },
    { stop: 'Foster Rd & Idyllwild Dr', id: '8083' },
    { stop: 'Foster Rd & Idyllwild Dr', id: '8084' },
    { stop: 'Foster Rd & Algonquin Rd', id: '8085' },
    { stop: 'Foster Rd & Algonquin Rd', id: '8086' },
    { stop: 'Foster Rd 900 Block', id: '8087' },
    { stop: 'Foster Rd & Swisher St', id: '8088' },
    { stop: 'Swisher St & Foster Rd', id: '8089' },
    { stop: 'Walker Circle & Moses Bloom Ln', id: '8090' },
    { stop: 'Grand Ave & South Grand-UIHC Emergency Entrance', id: '8100' },
    { stop: 'UI Family Care', id: '8101' },
    { stop: 'UIHC Family Care', id: '8102' },
    { stop: 'Melrose Ave & South Grand Ave', id: '8103' },
    { stop: 'Melrose Ave & Hawkins Dr', id: '8104' },
    { stop: 'Melrose Ave & Golfview Ave', id: '8105' },
    { stop: 'Melrose Ave & Koser Ave', id: '8106' },
    { stop: 'Melrose Ave & George St', id: '8107' },
    { stop: 'Melrose Ave & George St', id: '8108' },
    { stop: 'Sunset St & Melrose Ave', id: '8109' },
    { stop: 'Sunset St & Melrose Ave', id: '8110' },
    { stop: 'Sunset St & Marietta Ave', id: '8111' },
    { stop: 'Sunset St & Marietta Ave', id: '8112' },
    { stop: 'Sunset St & Oakcrest St', id: '8113' },
    { stop: 'Sunset St & Oakcrest St', id: '8114' },
    { stop: 'Oaknoll Retirement Center #1', id: '8115' },
    { stop: 'Oaknoll Retirement Center #2', id: '8116' },
    { stop: '945 Oakcrest St ', id: '8117' },
    { stop: 'Oakcrest St & Woodside Dr', id: '8118' },
    { stop: '815 Oakcrest St ', id: '8119' },
    { stop: 'Woodside Place & Greenwood Dr', id: '8120' },
    { stop: 'Greenwood Dr & Benton St', id: '8121' },
    { stop: 'Benton St @ Seville Apartments', id: '8122' },
    { stop: 'Benton St & Oaknoll Dr', id: '8123' },
    { stop: 'Benton St & George St', id: '8124' },
    { stop: 'Benton St & Streb St', id: '8125' },
    { stop: 'Sunset St & Arbury Dr', id: '8126' },
    { stop: 'Sunset St & Penfro Dr', id: '8127' },
    { stop: 'Sunset St & Denbigh Dr', id: '8128' },
    { stop: 'Sunset St & Aber Ave', id: '8129' },
    { stop: 'Melrose Ave & Sunset St', id: '8150' },
    { stop: 'Newton and Valley', id: '8200' },
    { stop: 'Newton Rd- Dental College', id: '8201' },
    { stop: 'Elliot St @ Carver Hawkeye Arena', id: '8202' },
    { stop: 'Hawkins Dr - UI Main Hospital, Kinnick Stadium', id: '8203' },
    {
      stop: 'Hawkins Dr - UI Center for Disabilities, Dental College',
      id: '8204'
    },
    { stop: 'Hawkins Dr & Melrose Ave-UI Childrens Hospital', id: '8205' },
    { stop: 'Hawkins Dr - UI Main Hospital, Kinnick Stadium', id: '8206' },
    { stop: 'Melrose Ave & Sunset St', id: '8208' },
    { stop: 'Melrose Ave & Emerald St', id: '8209' },
    { stop: 'Melrose Ave @ IC Fire Station #2', id: '8210' },
    { stop: 'Melrose Ave & Westgate St', id: '8211' },
    { stop: 'Westgate St & Melrose Ave', id: '8212' },
    { stop: 'Melrose Ave & Macbride Rd', id: '8213' },
    { stop: 'Melrose Ave & MacBride Rd', id: '8214' },
    { stop: 'Melrose Ave & Finkbine Ln', id: '8215' },
    { stop: 'Melrose Ave & Finkbine Ln', id: '8216' },
    { stop: 'Melrose Ave & Morman Trek Blvd', id: '8217' },
    { stop: 'Morman Trek Blvd & Melrose Ave', id: '8218' },
    { stop: 'Melrose Ave & Westwinds Dr', id: '8219' },
    { stop: 'Westwinds Dr & Willowwind Place', id: '8222' },
    { stop: 'Westwinds Dr & Hawaii Court', id: '8223' },
    { stop: 'Westwinds Dr & Roberts Rd', id: '8224' },
    { stop: 'Pheasant Ridge Neighborhood Center', id: '8226' },
    { stop: 'Bartelt Rd & Morman Trek Blvd', id: '8227' },
    { stop: 'Mormon Trek Blvd & Cameron Way -Walden Plaza', id: '8228' },
    { stop: 'Westwinds Dr - Walden Plaza', id: '8229' },
    { stop: 'Westwinds Dr #2', id: '8230' },
    { stop: 'Westwinds Dr #3', id: '8231' },
    { stop: 'Benton St & Spencer Dr', id: '8232' },
    { stop: 'Benton St & Keswick Dr', id: '8233' },
    { stop: 'Benton St & Westgate St', id: '8234' },
    { stop: 'Westgate St & Benton St', id: '8235' },
    { stop: 'Benton St - Horn Elementary', id: '8236' },
    { stop: 'Denbigh & Derwin', id: '8237' },
    { stop: 'Denbigh Dr & Hafor Dr', id: '8238' },
    { stop: 'Denbigh Dr & Penkridge Dr', id: '8239' },
    { stop: 'Denbigh Dr & Sunset St', id: '8240' },
    { stop: 'William St & Bradford Dr - SEJH', id: '8241' },
    { stop: 'Westwinds Dr & Melrose Ave', id: '8242' },
    { stop: 'Sunset St & Kineton Green', id: '8243' },
    { stop: 'Crosspark Ave & Broadway St', id: '8244' },
    { stop: 'Sunset St & Arbury Dr', id: '8245' },
    { stop: 'Benton St & Sunset St', id: '8246' },
    { stop: 'Sunset St & Benton St', id: '8247' },
    { stop: 'Westgate St & Westgate Circle', id: '8249' },
    { stop: 'Westgate St Midblock', id: '8250' },
    { stop: 'Westgate St & Keswick Dr', id: '8252' },
    { stop: 'Westgate St & Keswick Dr', id: '8253' },
    { stop: 'Westgate St & Gilmore Court', id: '8254' },
    { stop: 'Westside Dr & Earl Rd', id: '8270' },
    { stop: 'Westside Dr & Jeffrey St', id: '8271' },
    { stop: 'Westside Dr & Earl Rd', id: '8272' },
    { stop: 'Westside Dr & Morman Trek Blvd', id: '8273' },
    { stop: 'Morman Trek Blvd & Gryn Dr', id: '8275' },
    { stop: 'Mormon Trek and Plaen View', id: '8279' },
    { stop: 'Mormon Trek and Abbey ', id: '8281' },
    { stop: 'Morman Trek Blvd & Cae Dr', id: '8286' },
    { stop: 'Morman Trek Blvd & Benton St', id: '8290' },
    { stop: 'Benton St & Jema Court', id: '8291' },
    { stop: 'Melrose Ave & Hawkeye Dr', id: '8300' },
    { stop: 'Melrose Ave & Hawkeye Dr', id: '8301' },
    { stop: 'Melrose Ave & Dublin Dr', id: '8302' },
    { stop: 'Melrose Ave & Dublin Dr', id: '8303' },
    { stop: 'Melrose Ave & Kennedy Parkway', id: '8304' },
    { stop: 'Melrose Ave & Galway Dr', id: '8305' },
    { stop: 'Chatam Oaks Residential Facility', id: '8306' },
    { stop: 'Mormon Trek & Bartelt Rd', id: '8330' },
    { stop: 'Mormon Trek Blvd & Rohret Rd', id: '8331' },
    { stop: 'Coll Dr & Coll Court', id: '8332' },
    { stop: 'Jensen St & Jensen Court', id: '8333' },
    { stop: 'Irving Ave & Shannon Dr', id: '8334' },
    { stop: 'Shannon Dr & Rohret Rd', id: '8335' },
    { stop: 'Rohret Rd & Duck Creek Dr', id: '8336' },
    { stop: 'Deerfield Dr & Duck Creek Dr', id: '8337' },
    { stop: 'Duck Creek Dr & Partridge Court', id: '8338' },
    { stop: 'Duck Creek Dr & Wild Prairie Dr', id: '8339' },
    { stop: 'Wild Prairie Dr & Prairie Grass Ln', id: '8340' },
    { stop: 'Laredo Dr & Santa Fe Dr', id: '8342' },
    { stop: 'Santa Fe Dr & Phoenix Dr', id: '8343' },
    { stop: 'Phoenix Dr & Tuscon Place', id: '8344' },
    { stop: 'Phoenix Dr & Rohret Rd', id: '8345' },
    { stop: 'Rohret Rd - Irving Weber School', id: '8346' },
    { stop: 'Rohret Rd & Hunters Run', id: '8347' },
    { stop: 'Rohret Rd & Duck Creek Dr', id: '8348' },
    { stop: 'Rohret Rd & Shannon Dr', id: '8349' },
    { stop: 'Rohret Rd & Ranier Dr', id: '8350' },
    { stop: 'Arlington Dr & Chandler Ct', id: '8351' },
    { stop: 'Court St & Peterson', id: '8354' },
    { stop: '1st Ave & Stuart Court', id: '9001' }
  ];

  const done = (err, res) =>
    callback(null, {
      statusCode: err ? '400' : '200',
      body: err ? err.message : JSON.stringify(res),
      headers: {
        'Content-Type': 'application/json'
      }
    });
  // Uncomment and edit to make your own intent handler
  // uncomment `intentMap.set('your intent name here', yourFunctionHandler);`
  // below to get this function to be run when a Dialogflow intent is matched
  async function busStopHandler(agent) {
    const stop = agent.parameters['bus-stop'];
    const stopnum = stops.find(a => a.stop.eq === stop).id;
    const options = {
      url: ` http://api.ebongo.org/prediction?stopid=${stopnum}&api_key=XXXX`,
      headers: { 'User-Agent': 'AWS Lambda' }
    };
    const response = await request(options);
    const predictions = response.predictions.slice(0, 5);
    let builder = '';
    predictions.forEach(element => {
      builder += `${element.title} in ${element.minutes} minutes `;
    });
    returnJSON.fulfillmentText = 'yes response' +builder;
    returnJSON.payload = {
      google: {
        expectUserResponse: true,
        richResponse: {
          items: [
            {
              simpleResponse: {
                textToSpeech: 'this is a simple response' + builder
              }
            }
          ]
        }
      }
    };
    return done(null, returnJSON);
  }

  // Uncomment and edit to make your own Google Assistant intent handler
  // uncomment `intentMap.set('your intent name here', googleAssistantHandler);`
  // below to get this function to be run when a Dialogflow intent is matched
  function googleBusStopHandler(agent) {}
  // See https://github.com/dialogflow/dialogflow-fulfillment-nodejs/tree/master/samples/actions-on-google
  // for a complete Dialogflow fulfillment library Actions on Google client library v2 integration sample
  let returnJSON = new Object();
  console.log(typeof event);
  let body = event.body;
  switch (body.queryResult.intent.displayName) {
    case 'Bus Stop Prediction': {
      await busStopHandler(body.queryResult);
    }
  }
  // Run the proper function handler based on the matched Dialogflow intent name
};
